name: Update Major Release Tag

on:
  release:
    types: [created]

permissions: {}

jobs:
  update-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Get major version num and update tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR=${VERSION%%.*}
          git config --global user.name "GitHub Actions"
          echo "Updating ${MAJOR} tag"
          git tag -fa ${MAJOR} -m "Update major version tag"
          git push origin ${MAJOR} --force
